### ISSUE TITLE
warnings in terminal [GLib-GIO-WARNING ]

### ISSUE THREAD

**Issue by mbkma** [mate-desktop/mate-calc#110]
#### Expected behaviour
No warning messages.

#### Actual behaviour
Warning-message:

`
(mate-calc:3881): GLib-GIO-WARNING **: 22:58:34.261: g_settings_set_value: value for key 'accuracy' in schema 'org.mate.calc' is outside of valid range`

#### Steps to reproduce the behaviour
I noticed the above message in mate-calc when run from command line and setting the decimal places greater than 9 in preferences dialog. Most certainly caused by #86.

#### MATE general version
mate-calc git master 

#### Package version
locally compiled

#### Linux Distribution
UM 18.04

**Comment by flexiondotorg** [comment]
Pull request #86 is not in mate-calc 1.20.

**Comment by mbkma** [comment]
yeah, I noticed this in master (self compiled), not in mate calc 1.20. That's why I wrote package version: master

**Comment by vkareh** [comment]
@mbkma, sounds like when you compiled your package, you did not re-compile the schema files. Try running:
```bash
sudo cp ./data/org.mate.calc.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by mbkma** [comment]
@vkareh  yes, that was it indeed, I am sorry.
