### ISSUE TITLE
Programmer mode binary display is incorrect with negative numbers

### ISSUE THREAD

**Issue by acscd** [mate-desktop/mate-calc#125]
Expected behavior:
When the result is a negative number, I would expect the binary display to show an accurate representation of that number as stored by the computer. e.g. -47 should show up as 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1101 0001 on an x86-64 machine.
Alternately, though I think it would be far less useful for a programmer (though making some mathematicians happy), it could just display a signed binary number: -47 would be -101111.

Actual behavior:
Negative results show up as all 0s in the binary display.

Make sure it's set to Programming mode. Enter a negative number or calculation with a negative result.

MATE general version 1.22
Package version: 1.22.2-1
Linux Distribution: Manjaro x86-64

**Comment by rbuj** [comment]
This is `ones (47)`:

![Screenshot at 2020-01-18 20-14-14](https://user-images.githubusercontent.com/10171411/72669217-67594900-3a2f-11ea-8906-707223d745ac.png)

**Comment by acscd** [comment]
Okay, interesting... So twos() or ones() gives a correct binary view, while simply entering a negative gives all zeros. It doesn't really make sense to me, but that's fine.

A very closely related issue I just found while playing with this though: in any number format except Fixed, twos() or ones() also gives all zeros, **until you switch to _any_ other number format!**
