### ISSUE TITLE
History View

### ISSUE THREAD

**Issue by equasman** [mate-desktop/mate-calc#131]
#### Expected behaviour
The History View should locate above the entry box and be designed to show previous calculations in the form of a scrollable list that can be clicked and scrolled through using a mouse or even navigated and selected using the arrow keys on a keyboard.
Once an entry has been selected, it will immediately show up in the entry box for to manipulate and use.
Finally, there is no upper limit on the number of calculations that can show up in the list for use.

#### Actual behaviour
We can only access history in the MATE Calculator using the kayboard shortcut Undo command (**Ctrl**+**Z**)

#### Steps to reproduce the behaviour
Open MATE Calculator and do some calculations.

#### Package version
mate-calc 1.20.3

#### Linux Distribution
Debian 10.1

**Comment by mbkma** [comment]
Just want to state that I have nothing to do with this feature request :grin:
@equasman you might want to take a look at #129

**Comment by equasman** [comment]
Oh, my bad. I didn't see that issue opened.
Thanks for the implementation.
