### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by es20490446e** [mate-desktop/mate-calc#132]
[This](https://forum.manjaro.org/uploads/default/original/3X/3/f/3feb0d95e5e3afbee8a4fd595b6280977037ebf0.png) while using some fonts as system font (like Noto Sans), but not with others (like Liberation Sans) .

Not any other application shows the behavior, including Pluma. They all show the symbols.

**Comment by es20490446e** [comment]
I also see [this](https://i.imgur.com/nPpl1wb.png) on Pluma. The symbol is show correctly in the text, but not on the search box.

**Comment by es20490446e** [comment]
Some locale files seems to have empty msgstr variables. For example:
- Good: [es_AR.po](https://github.com/mate-desktop/mate-calc/blob/master/po/es_AR.po)
- Bad: [es_CO.po](https://github.com/mate-desktop/mate-calc/blob/master/po/es_CO.po)

**Comment by es20490446e** [comment]
It also happens [this other bug](https://youtu.be/h05m7e5QR0I), which I believe is related with the first as none of them seem to appear in another computer I have.

By the way if you put a label on a bug report I won't simply notice, as I won't receive any email as result.

The template is ignored on purpose, as I don't see how that extra information would help. I'm using the latest stable version of the calculator, as I'm on a rolling release distro.

**Comment by raveit65** [comment]
template ignored = unsubscribed!

**Comment by es20490446e** [comment]
mate-calculator 1.22.2

What else do you need?

**Comment by rbuj** [comment]
Apparently your system locale is not correctly configured. The decimal separator was set to full stop symbol "." in mate calc window on your screencast (English locale), whereas you used the comma symbol "," as a decimal separator (Spanish, Portuguese, ...  locale).

Test: Set your locale on command line as follows:

**Spanish**
```
$ LANG=es_ES.UTF-8 mate-calc
```
**Portuguese**
```
$ LANG=pt_BR.UTF-8 mate-calc
```
I was unable to reproduce your issue using English, Spanish, Portuguese locale settings.

**Comment by es20490446e** [comment]
Likely. I will investigate 👍

**Comment by es20490446e** [comment]
It was due to a [bug](https://forum.manjaro.org/t/noto-fonts-broken-fallback-fonts/126583) in the noto-fonts package.
