### ISSUE TITLE
[atan] arctan does not get calculated correctly

### ISSUE THREAD

**Issue by pepper-jk** [mate-desktop/mate-calc#166]
#### Expected behaviour
`atan(2) / 2 = 0.553574359`
https://www.wolframalpha.com/input/?i=atan%282%29+%2F+2

#### Actual behaviour
`atan(2) / 2 = 31.717474411`

#### Steps to reproduce the behaviour
Enter `atan(2) / 2` and hit Enter.

#### MATE general version
1.24.0

#### Package version
1.24.0-1

#### Linux Distribution
Arch Linux

**Comment by rbuj** [comment]
31.717474411 degrees = 0.553574359 radians

**Comment by pepper-jk** [comment]
> 31.717474411 degrees = 0.553574359 radians

oh sorry, my bad

**Comment by pepper-jk** [comment]
I guess it could be made more obvious though what unit is displayed.
Maybe switch the unit in the drop down menu to degrees automatically or something.

**Comment by rbuj** [comment]
<img width="1014" alt="Captura de Pantalla 2020-06-17 a les 22 28 38" src="https://user-images.githubusercontent.com/10171411/84947084-ef7c7100-b0e9-11ea-8b51-961aeb56335c.png">

**Comment by pepper-jk** [comment]
Well for me it does not switch automatically to degrees, when I calculate "atan".
Even with "number format" on "automatic".
I am aware of the manual functionality though, thanks.
