### ISSUE TITLE
incorrect parenthesis handling

### ISSUE THREAD

**Issue by ZuseZ4** [mate-desktop/mate-calc#167]
#### Expected behaviour
1) Calculate 6+2,33*sqrt(2,5)+6 (= 6 + 3,68 + 6 = 15,68)
2) Calculate 6+2,33*ln(2,5)+6 (=6 + 2,13 + 6 = 14,13)
#### Actual behaviour
1) Returns 23,664053474 which corresponds to 6+2,33*(sqrt(2,5)+6)
2) Returns 22,114957405 which corresponds to 6+2,33*(ln(2,5)+6)

#### Steps to reproduce the behaviour
Just try it

#### MATE general version
Release 20.04 LTS (Focal Fossa) 64-bit
Kernel Linux 5.4.0-37-generic x86_64

#### Package version
1.24.0
Default settings:
Number Format Automatic,
Showing 9 decimal places,
Angle units: Degrees,
Word size 64-bit
Mode Basic (same results in other modes)

#### Linux Distribution
Ubuntu 20.04 Mate

#### Link to downstream report of your Distribution

Verified wrong results on a second PC using a clean Ubuntu 20.04 in Virtualbox
Verified correct results on a third PC using mate-calc 1.20.1 on Ubuntu 18.04

**Comment by mbkma** [comment]
This is not good. Introduces by commit 731bdfe3591618759a44d9382b49952e781a01bd.
