### ISSUE TITLE
Calculation order error

### ISSUE THREAD

**Issue by trebmaLneB** [mate-desktop/mate-calc#180]
#### Expected behaviour
Input:
6*cos(45) +1
Correct answer is 5.2426406... (assuming working in degrees)
#### Actual behaviour
6*cos(45) +1
yields:
10,242640687
However, this is the correct answer for
6*(cos(45)+1)
(in degrees), so clearly there are problems with calculation order here. Similar errors occur for 6*cos(45)+sin(45) (which gives a number over 8, clearly wrong as the absolute value of both sine and cosine is less than or equal to 1)
#### Steps to reproduce the behaviour
Just typing it in to the calculator. 
#### MATE general version
1.24.0
#### Package version
1.24.0-1
#### Linux Distribution
Xubuntu 20.04.1 LTS (Focal Fossa)

**Comment by mbkma** [comment]
Thanks for reporting :+1:  This issue is fixed in version 1.24.1. I think it depends on your distribution when you will get it.
