### ISSUE TITLE
Convergence issue with the ln function

### ISSUE THREAD

**Issue by jVictor3447** [mate-desktop/mate-calc#187]
#### Expected behaviour
ln(1/2) should output -ln(2) which is about -0.693

#### Actual behaviour
Gives error message: ERROR OCCURRED IN MP_LNS, NEWTON ITERATION NOT CONVERGING PROPERLY

#### Steps to reproduce the behaviour
Just type into the app

#### MATE general version
1.24

#### Package version
1.24-1

#### Linux Distribution
Xubuntu LTS 20.04

#### Link to bugreport of your Distribution (requirement)
https://launchpad.net/ubuntu/+bugs

**Comment by mbkma** [comment]
Thank you for reporting this issue. This bug has been solved with the migration of `mate-calc` to the GNU MPFR library (https://github.com/mate-desktop/mate-calc/commit/b0117b1d5ae73916c6f0d289be1f693bb5f46824) and will be available in the next stable release of MATE.
