### ISSUE TITLE
mpc is required, but not searched

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-calc#192]
src/mp.h requires mpc.h, but this header not checked by configure.
mpfr not depends on mpc, so this I think, checking for mpc.h is required.

**Comment by mbkma** [comment]
yes it is: https://github.com/mate-desktop/mate-calc/blob/e3ea3965890dcbccc9a7d2958472f0ed46b872fc/configure.ac#L48

**Comment by rezso** [comment]
Not enough. Without installed mpc headers (mpc devel package), the build fails:

`make  all-am
make[3]: Entering directory '/var/uhubuild/work/compile/src'
  CC       mate-calc.o
  CC       currency.o
  CC       currency-manager.o
  CC       math-buttons.o
In file included from currency.h:15,
                 from currency.c:14:
mp.h:38:10: fatal error: mpc.h: Nincs ilyen fájl vagy könyvtár
   38 | #include <mpc.h>
      |          ^~~~~~~
compilation terminated.
make[3]: *** [Makefile:877: currency.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from currency.h:15,
                 from currency-manager.h:14,
                 from currency-manager.c:21:
mp.h:38:10: fatal error: mpc.h: Nincs ilyen fájl vagy könyvtár
   38 | #include <mpc.h>
      |          ^~~~~~~
compilation terminated.
make[3]: *** [Makefile:877: currency-manager.o] Error 1
In file included from math-equation.h:18,
                 from math-buttons.h:16,
                 from math-buttons.c:13:
mp.h:38:10: fatal error: mpc.h: Nincs ilyen fájl vagy könyvtár
   38 | #include <mpc.h>
      |          ^~~~~~~
compilation terminated.
make[3]: *** [Makefile:877: math-buttons.o] Error 1
In file included from math-equation.h:18,
                 from math-window.h:16,
                 from mate-calc.c:18:
mp.h:38:10: fatal error: mpc.h: Nincs ilyen fájl vagy könyvtár
   38 | #include <mpc.h>
      |          ^~~~~~~
compilation terminated.
`

So I think, searching mpc is required in PKG_CHECK_MODULES (MATE_CALC, MATE_CALC_CMD).

**Comment by mbkma** [comment]
Which distro do you use? Which version of mate-calc? Which is the exact package name and version of mpc you installed?

**Comment by rbuj** [comment]
@rezso there is no pc file in the pkgconfig folder for the mpc library. Do you want to add a header check?
```diff
diff --git a/configure.ac b/configure.ac
index 47365ff..dac356a 100644
--- a/configure.ac
+++ b/configure.ac
@@ -46,6 +46,7 @@ AC_SUBST(GLIB_MKENUMS)
 
 AC_CHECK_LIB(m, log)
 AC_CHECK_LIB(mpc, log)
+AC_CHECK_HEADER([mpc.h], [], [AC_MSG_ERROR(could not find required headers for MPC)], [])
 
 dnl ###########################################################################
 dnl Internationalization
```

**Comment by rbuj** [comment]
The configure script execution can also be aborted if library checking failed:
```diff
diff --git a/configure.ac b/configure.ac
index 47365ff..313f226 100644
--- a/configure.ac
+++ b/configure.ac
@@ -45,7 +45,7 @@ GLIB_MKENUMS=`$PKG_CONFIG --variable=glib_mkenums glib-2.0`
 AC_SUBST(GLIB_MKENUMS)
 
 AC_CHECK_LIB(m, log)
-AC_CHECK_LIB(mpc, log)
+AC_CHECK_LIB(mpc, log, [], [AC_MSG_ERROR(could not find required development libraries for MPC)], [])
 
 dnl ###########################################################################
 dnl Internationalization
```
Test:
```
$ ./autogen.sh --prefix=/usr
<cut>
checking for log in -lmpc... no
configure: error: could not find required development libraries for MPC
```
