### ISSUE TITLE
Window all cut off on Librem 5/small screen

### ISSUE THREAD

**Issue by programmin1** [mate-desktop/mate-calc#194]
#### Expected behaviour
All modes should work, all features should work.

#### Actual behaviour
Only BASIC mode works and only in Landscape mode, on the Librem 5 phone. On Pinephone and others it will probably be the same issue. I wrote up how I was able to fix this type of issue on a posting here: https://howtotrainyourrobot.com/building-an-amateur-radio-app-for-librem-phone-part-3/

#### Steps to reproduce the behaviour
Install MATE calculator. Try different modes.

#### MATE general version
Mate-calc 1.20.3

#### Package version
Mate-calc 1.20.3

#### Linux Distribution
PureOS

#### Link to bugreport of your Distribution (requirement)
https://source.puri.sm/Librem5/phosh/-/issues/550

**Comment by mbkma** [comment]
I do not think that adaptive applications belong to a desktop environment like MATE optimized for working on a computer/notebook. If you need apps for mobile phones, there are enough specialized apps which are optimized to work in a mobile environment. Do one thing and do it well :)

**Comment by programmin1** [comment]
The Librem 5 is technically a desktop environment, whenever I am home and plug it in to the USBC dock with keyboard+mouse+screen. So how would you like it if you have an app that works on one size screen, but not when you use another...? Your app works when you have it on one of your screens but if you drag it to the other screen it gets all messed up?
Also to be honest I think more people are familiar with using a calculator on a small calculator-sized object than typing on a keyboard and then looking up at the big computer screen.

**Comment by vkareh** [comment]
MATE doesn't (and shouldn't) address adaptive applications. There are other desktop environments more suited for adaptive/touchscreen/small screens, MATE is not geared towards that.
