### ISSUE TITLE
mate-calc: issues with Russian localization - not translated items

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/mate-calc#206]
#### Expected behaviour
The following items are expected to be translated to Russian:

Menu "**Calculator**", (RU: "**Калькулятор**")
- Clear History

Menu "**View**", (RU: "**Вид**")
- History

#### Actual behaviour
Even with
```
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU.UTF-8
```
the following items are left in English

Menu "**Calculator**", (RU: "**Калькулятор**")
- Clear History

Menu "**View**", (RU: "**Вид**")
- History

#### Steps to reproduce the behaviour
Run `mate-calc`, check menus "**Calculator**" and  "**View**".

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu 21.10 with latest updates

**Comment by raveit65** [comment]
Again, we're using transifex for our translations. We can't fix it here !
Please become a member of your language team at transifix and fix translations there.
https://www.transifex.com/mate/MATE/languages/
