### ISSUE TITLE
Error with log()

### ISSUE THREAD

**Issue by Jean-PierreBONNEMAISON** [mate-desktop/mate-calc#220]
#### Expected behaviour
Computing `log(115/70)` should work.
It does work with 113, 114, 116, 117, etc.

#### Actual behaviour
*** ERROR OCCURED IN MP_LNS, NEWTON ITERATION NOT CONVERGING PROPERLY ***

#### Steps to reproduce the behaviour
log(115/70)

#### Package version
1.24.0

#### Linux Distribution
Xubuntu 20.04

**Comment by cwendling** [comment]
I don't have 1.24 at hand, but this seems to work fine for me both with 1.20 (Debian buster) and 1.26 (Debian testing).  Gives 0,2155998, which seems reasonable for log10.

**Comment by zhuyaliang** [comment]
Please review [b0117b1d](https://github.com/mate-desktop/mate-calc/commit/b0117b1d5ae73916c6f0d289be1f693bb5f46824)

**Comment by cwendling** [comment]
@zhuyaliang this doesn't explain why it works for me with 1.20 as well though, does it?

**Comment by zhuyaliang** [comment]
@cwendling After searching for the code, it was found that a code commit [1957af0e](https://github.com/mate-desktop/mate-calc/commit/1957af0ef634a426c45d777a7a1000c726c3ff71) after 1.22 caused this issue

**Comment by mbkma** [comment]
This version is not supported anymore.
