### ISSUE TITLE
Make Calc’s window actually resizable again?

### ISSUE THREAD

**Issue by scytho** [mate-desktop/mate-calc#222]
This is a general thing, so I am omitting the template.

I have been using Gnome 2 and than Mate for about 15 years now. Back in the day (Ubuntu 10.04?), the calculator used to have a really convenient way of resizing and reorganising the entire GUI when the window was being resized. Over the years, this became less and less the case. Now (version 41.1), when you resize the window, really only the window itself is being resized, not its content. Why is that? Because of this, there is now way of making long expressions visible in their entirety. Apart from that, the titlebar with its strange menus is completely braking with the design of the Mate GUI style. This is one of the many things in which the dissipation of Mate’s essence is manifesting itself, which was continuing Gnome 2’s standards.

:´(

**Comment by lukefromdc** [comment]
I just confirmed the resize issue. As for the rest, how is it that you are getting titlebars with menus on mate-calc? What distro and what window manager?

If you are using mate-calc on a GNOME
desktop this would not be surprising but I've never once seen mate-calc with a headerbar (client-side decorated,
takes the oversize title bar that can carry menubuttons) myself.

**Comment by lukefromdc** [comment]
I do not see how you are getting client-side decoration at all, yet your screenshot shows that's exactly what you are getting. Are you using Cinnamon or MATE for a desktop environment? If the former there may be an issue on that end causing the CSD titlebar. Also, open dconf-editor and navigate to /org/mate/desktop/interface/gtk-dialogs-use-header and make sure that is turned OFF. I am wondering if this is somehow getting mistaken for a dialog.

The contents not being resizable I can confirm is an issue though

**Comment by scytho** [comment]
Interesting. I thought this was all on purpose. It has been like this for a long time. I am sure it was the same or very similar when I was running Mint 20. Actually, I still have it. I can boot it an check mate-calc there (not today, though).

As I said, I am on Mint 21.3 with Mate 1.26.0. I just checked, /org/mate/desktop/interface/gtk-dialogs-use-header was and is turned off. There is no other DE installed. mate-calc looked like that out of the box, I am pretty sure.

**Comment by lukefromdc** [comment]
What is your exact GTK version? Wondering if there is an issue with how your GTK version or build is handling this. What is your window manager? Are you using marco, marco with hardware compositing (compton?), compiz, or something else? Most certainly no change in mate-calc would produce these headerbars.

Do you know for sure this is mate-calc and not one of Mint's Xapps, gnome-calc, or something else? Also, wondering if Mint is patching mate-calc in some way that causes the headerbars. 

I can't duplicate your setup as I don't have a landline to download installers over

**Comment by scytho** [comment]
Regarding GTK, how can I find that out? marco is installed, so I guess this is the active window manager. I am using the desktop as shipped, no compiz tinkering or something like that.

I am looking at three Mint installs: 19.3, 20 and 21.3. It is all somewhat mysterious. I was wrong, under Mint 19.3 the calculator scaled OK. And you are right, it is not mate-calc, it is gnome-calc on 20 and 21.3. I assumed it was mate-calc since it is Mate. For Mint 19.3 I have to reboot again, but I guess it’ll be gnome-calc, too.

I just installed mate-calc (on 21.3, and the version is 1.26.0, same as Mate). It looks quite different. The window is not resizable, unless history is enabled.
![mint_21 3_mate_1 26 0_mate-calc_1 26 0_2024-06-20a](https://github.com/mate-desktop/mate-calc/assets/13711754/6d3b001c-ad69-4183-bd83-867b63f8be17)
![mint_21 3_mate_1 26 0_mate-calc_1 26 0_2024-06-20b](https://github.com/mate-desktop/mate-calc/assets/13711754/4f9098d0-a4e3-4e46-a0fb-9aa8a1f6220f)
So, I guess we can close this. I just don’t see why Mint Mate is shipped with gnome-calc instead of mate-calc.

BTW: What is client-side decoration?

**Comment by lukefromdc** [comment]
Client side decoration means the window manager does NOT draw the borders, instead the application does. GNOME uses it to allow putting what would normally be half the menubar or toolbar items into the top window border.  It also has a long history in single apps, notably in Chrome/Chromium as an option, which of course was later copied by Firefox.
