### ISSUE TITLE
Mate-calc going away? Galculator lacks financial and programmer features.

### ISSUE THREAD

**Issue by dcharlespyle** [mate-desktop/mate-calc#24]
Wasn't sure where to put this but I just read that mate-calc is going away and will be replaced with Galculator in mate-desktop 1.10.  I have made use of the programming and financial functions in mate-calc.  Galculator lacks those features, so this basically amounts to a feature loss in mate-desktop 1.10, which will become an issue in the near future.  Or, will the code for these functions be added to the codebase of Galculator to integrate those features into Galculator? Please advise.

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.
