### ISSUE TITLE
Incorrect result for 2^(-55)

### ISSUE THREAD

**Issue by doug65536** [mate-desktop/mate-calc#25]
Incorrect result for 2^(-55).

mate-calc result = 0
expected result = 2.7755575615628914e-17

Upon further investigation:
2^-30 results in 0.000000001
2^-31 results in 0

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.

**Comment by scrupeus** [comment]
The result is actually correct - see #38 for an explanation and partial solution and #39 for another solution.

**Comment by sc0w** [comment]
confirmed, `mate-calc` shows 0 and `galculator` shows the expected result mentioned
