### ISSUE TITLE
Incorrect result for 1/10^10

### ISSUE THREAD

**Issue by doug65536** [mate-desktop/mate-calc#26]
mate-calc result = 0
expected result = 1e-10

**Comment by doug65536** [comment]
?

**Comment by monsta** [comment]
This package is discontinued after 1.8.
http://mate-desktop.com/blog/2014-03-17-galculator-is-coming-to-mate/

**Comment by doug65536** [comment]
Oh, okay. Thanks.

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.

**Comment by scrupeus** [comment]
Actually the answer is correct, but...
The display is limited to a maximum of 9 decimal places and thus the following '1' is truncated.  You can confirm by multiplying the result by 10^10 and returning to 1.
See #38 and #39 for solutions.

**Comment by sc0w** [comment]
confirmed, `mate-calc` shows 0 and `galculator` shows the expected result mentioned

**Comment by lukefromdc** [comment]
Closed with 
https://github.com/mate-desktop/mate-calc/pull/98
