### ISSUE TITLE
Can't change menu shortcut

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-calc#30]
Hello

It appear that with mate-calc 1.8.0-0+qiana (i don't found the debian package...) I can't change accels in menu (for eaxample o remove F1 for Help).

Can mate-calc honor "can-change-accels" from dconf?

**Comment by monsta** [comment]
This package is discontinued after 1.8.
http://mate-desktop.com/blog/2014-03-17-galculator-is-coming-to-mate/

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.

**Comment by monsta** [comment]
Since "can-change-accels" doesn't work with GTK+3 at all anymore, we can close this.
