### ISSUE TITLE
Incorrect result for -ln(x)

### ISSUE THREAD

**Issue by maandree** [mate-desktop/mate-calc#31]
-ln(x) is parsed as ln(-1)+ln(x) (somehow), leading silly ludicrous
result such as −ln(1) = πi, or −ln(2) ≈ 0,693147181 + πi.

**Comment by monsta** [comment]
This package is discontinued after 1.8.
http://mate-desktop.com/blog/2014-03-17-galculator-is-coming-to-mate/

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.

**Comment by sc0w** [comment]
@maandree please can you explain better the issue?

we need to reproduce the issue step by step:

- expected behavior

- actual behavior

**Comment by rbuj** [comment]
### expected behavior
-ln(1) = -1 x ln(1) = -1 x 0 = 0. ln(1)=0, e^0=1
-ln(e) = -1 x ln(e) = -1 x 1 = -1. ln(e)=1, e^1=e
1-ln(e) = 0 = 1 - 1 = 0

### actual behavior
-ln(1) = 3.141592654i. e^3.141592654i = -1
-ln(e) = 1+3.141592654i. e^(1+3.141592654i) = -e
1-ln(e) = 2.151×10⁻³⁹⁷

**Comment by sc0w** [comment]
@rbuj which `mate-calc` version did you test that values?

**Comment by rbuj** [comment]
latest build from master
https://gist.github.com/rbuj/bc62164be10a7290f5213c47711c7998#file-test-mate-desktop-sh

**Comment by sc0w** [comment]
ok, with mate-calc 1.20.3 the values are different (not sure, probably https://github.com/mate-desktop/mate-calc/commit/b0e4fe242b2b7b0a980d163bbf294f588b084091 makes the difference)

```
mate-calc 1.20.3

-ln(1) = 3.141592654i
-ln(e) = 1+3.141592654i
1-ln(e) = 0

```
```
gnome-calculator 3.30.1

-ln(1) = 0
-ln(e) = -1
1-ln(e) = 0
```

**Comment by sc0w** [comment]
@rbuj these are the expected values?
```

-ln(1) = 1
-ln(e) = e
1-ln(e) = 0
```

**Comment by rbuj** [comment]
@sc0w 
```
-ln(1) = 0
-ln(e) = -1
1-ln(e) = 0
```
Formula
```
ln(x) = y
e^y = x
```

**Comment by sc0w** [comment]
ok, my tests:

**gnome-calculator** versions:

**3.10.0 it works** as expected

**3.8.2** shows the same **wrong** values  as mate-calc 1.20.3

**Comment by mbkma** [comment]
I think it was fixed by this commit: https://gitlab.gnome.org/GNOME/gnome-calculator/commit/917fafcb062412c66230bde4cfed5437ba0da235

**Comment by mbkma** [comment]
For example, these test cases from the commit still do not work in mate-calc:

```
    test ("1 + 2 - 3 * 4 / 5", "0.6", 0);
    test ("10 mod 4 / 2", "1", 0);
    test ("20 / 10 mod 3", "2", 0);
    test ("12 / 3 √4", "8", 0);
    test ("√5!", "10.95445115", 0);
    test ("4 ^ sin 30", "2", 0);
    test ("4 ^ (sin 30)", "2", 0);
    test ("4 ^ sin (30)", "2", 0);
    test ("sin (30) ^ 4", "0.0625", 0);
    test ("sin 30 ^ 4", "0.0625", 0);
    test ("sin (30 ^ 4)", "0", 0);


```

At least the ones where there are missing brackets.
