### ISSUE TITLE
Feature Request: History panel

### ISSUE THREAD

**Issue by esemeniuc** [mate-desktop/mate-calc#32]
Having a history panel where you could go back to old equations or copy the expression/result would be super handy. An idea for implementation could be like the this example (http://www.eeweb.com/toolbox/calculator)

**Comment by raveit65** [comment]
Sorry, mate-calc i obsolete since 1.10.
The replacement is http://galculator.mnim.org/

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.

**Comment by Translator5** [comment]
Time passes - would be fantastique! :kissing_heart:
