### ISSUE TITLE
Size of result view

### ISSUE THREAD

**Issue by pavkamlc** [mate-desktop/mate-calc#33]
When I tried compute long term, Ive problem with displaying result. After typo many numbers with operations and push Enter to solve, result is out of text rectangle and cant be scrolled.

![mate-calc](https://cloud.githubusercontent.com/assets/1273709/13382106/b0fde3f4-de6c-11e5-8965-2a915a307ace.png)

**Comment by flexiondotorg** [comment]
`mate-calc` is deprecated and no longer developed or supported.

**Comment by flexiondotorg** [comment]
`mate-calc` is resurrected.

**Comment by monsta** [comment]
This is not reproducible anymore, probably it's a GTK+2 only bug.
