### ISSUE TITLE
Please install .appdata.xml file to correct metainfo location

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-calc#49]
In Debian, the .appdata.xml (apspstream) file goes into /usr/share/metainfo.

See here for the workaround, I currently have in debian/rules:
https://anonscm.debian.org/cgit/pkg-mate/mate-calc.git/commit/?id=b54b03e9ddf3fdff24b7e079e13bd1efa416e21d

**Comment by sc0w** [comment]
The url mentioned by @sunweaver don't work

The debian commit now is here:

https://salsa.debian.org/debian-mate-team/mate-calc/commit/b54b03e9ddf3fdff24b7e079e13bd1efa416e21d

**Comment by raveit65** [comment]
I think we have a similar commit from October in another repo to fix that.

**Comment by raveit65** [comment]
And cherry-picked to 1.20 branch.
