### ISSUE TITLE
Results could be pasteable into other applications

### ISSUE THREAD

**Issue by es20490446e** [mate-desktop/mate-calc#57]
HOW TO REPRODUCE:
1. Make an operation which result is negative.
2. Copy the result into a LibreOffice Calc box.

RESULT:
- LibreOffice doesn't understand the pasted number because of the minus sign being a dash, not an actual minus.

**Comment by abcdjdj** [comment]
I can confirm this bug. The problem is that mate-calc is displaying the unicode MINUS_SIGN (U+2212) character instead of the regular ASCII '-' (ASCII value 45). However I'm not too sure if this is a bug or intentional behaviour. If it's not intentional, I can send a PR.

**Comment by es20490446e** [comment]
The keyboard doesn't have an Unicode minus, so using that character should be inferred by the software itself.

And that cannot be done reliably in all contexts. For example, if you press the key "-" in a LibreOffice Calc cell it could mean both minus or hyphen.

So it appears that using ASCII is a better standard, as software would have it easier to interpret the meaning of the char after the hole line is written. Not before that.

This was decided by the GNOME developers, not Mate's.

**Comment by vkareh** [comment]
I traced this back and this change was done 9 years ago by GNOME here: https://gitlab.gnome.org/GNOME/gnome-calculator/commit/ecb40d6426eaf0e43ec385b26509d7260f36ad45 (then that sign gets passed on and moved files and so on until what we have today, if you follow the entire commit history)

There is no explanation as to why this was done, unfortunately. We can change it and see what happens, and do proper regression test.

**Comment by es20490446e** [comment]
@robert.ancell What's your opinion?

**Comment by es20490446e** [comment]
It doesn't seem that the entire commit should be reverted, as it seems it fixes UTF-8 handling somehow.

The only thing that needed to be changed is char "−" to "-".

**Comment by vkareh** [comment]
@es20490446e - the username is @robert-ancell on GitHub, but he's involved with GNOME, not MATE. Still it'd be awesome to get his perspective on this, even though this change was done almost a decade ago. :smile:

A quick grep of the codebase shows 548 instances of the Unicode `−` character, so just changing this line _might_ break some things we don't know about...

I'd say try it out and see what breaks!

**Comment by es20490446e** [comment]
I have emailed him.

**Comment by es20490446e** [comment]
I would wait a couple of days to see if Robert says something, and if he doesn't so I will just change it. Most likely it won't have any consequence.

Thanks for your help.

**Comment by robert-ancell** [comment]
The unicode characters are intentionally used so the maths looks corrrect (there's many other characters used besides minus). Note that the keyboard events are interpreted to input them - the input field is not just a simple entry.

The 100% correct fix would be for LibreOffice to handle the minus correctly, but if that seems unlikely then you might just want to update the copy-paste code to substitute MINUS_SIGN for '-'. That way it will look correct in the calculator but still work when copied to apps that don't handle Unicode correctly.

**Comment by es20490446e** [comment]
It's unlikely that LibreOffice will be able to interpret the key press correctly before evaluating the hole line.

The only thing that could be done there is to convert the Unicode minus into an hyphen, but it looks simpler to me just to use hyphen to begin with.

**Comment by es20490446e** [comment]
I have reported this issues that minus causes to the Unicode Consortium.

**Comment by belzecue** [comment]
I just encountered this character code issue when copy/pasting from Gnumeric 1.12.35 (Ubuntu 18.4.2) to GSheets.  In Google Sheets the result is an "em" dash (or maybe an "en" dash -- long dash) preceding the number instead of minus sign, so the cell is not interpreted as a negative number.  The only solution is to search/replace and swap the em-dash to a minus sign in Sheets.  See screenshot here: http://tinypic.com/r/14tswtd/9

**Comment by es20490446e** [comment]
@belzecue Well, you will want to report to Gnumeric then ;)
