### ISSUE TITLE
Static analyzer report

### ISSUE THREAD

**Issue by shlyakpavel** [mate-desktop/mate-calc#69]
#### Expected behaviour
Code is perfect :D

#### Actual behaviour
No code is perfect :) Even here in mate

#### Steps to reproduce the behaviour
Download the code and check it with a static analyzer

#### MATE general version
I have no mate installed

#### Package version
Latest git upstream

#### Linux Distribution
Xubuntu 16.04

#### Problems found:
1. Potentially uninitialized variable 'bits' used.
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/math-buttons.c#L391
2. lower_name is not null-safe. You should better check it against null
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/math-equation.c#L1108
3. Integer overflow handling seems to be incorrect here
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/mp.c#L1572
4. The expression is always false here. multiplier is set to zero and never modified.
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/mp-convert.c#L706
5. It is probably more logical to check both x and z instead of checking x twice. Copy-pasting is sometimes dangerous...
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/unit.c#L140-L145
6. This expression is overcomplicated. Consider making it `result!=expected`
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/test-mp.c#L136
7. Why does one set base to ten and then just reassign it to be binary?
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/test-mp-equation.c#L190-L197
8. I also do not like these `printf` here:
https://github.com/mate-desktop/mate-calc/blob/d0a089f1d26438f666bed293866751efaa568531/src/mate-calc.c#L75
I would either choose format first or go for `puts`. The current code here is neither buggy nor vulnerable but it is potentially dangerous if someone decides to modify it in the future. 
Thanks for providing useful and reliable software and have a nice day :)

**Comment by raveit65** [comment]
Can i send you the bill for working on that?

**Comment by sc0w** [comment]
@shlyakpavel which analyzer did you use here?

**Comment by shlyakpavel** [comment]
This must be already out of date
